### ISSUE TITLE
Add multiple projects

### ISSUE THREAD

**Issue by sparkmuse** [anaynayak/buildnotify#243]
I run in a microservice environment and I would like to add multiple projects at the same time without going through the UI and added them manually. 

Is this a feature that could be added?

**Comment by anaynayak** [comment]
If the CI server you use has a single cctray.xml feed, you can select the top level `all` checkbox and it should automatically load new projects. 

![image](https://user-images.githubusercontent.com/416211/162883093-1cf43585-d3f3-4ef6-8c6b-a2ed4695c68f.png)

**Comment by sparkmuse** [comment]
@anaynayak I am sorry I did not get a notification for this. 

We do not have a single cctray.xml feed.  I was thinking something similar to what mac users have for ccMenu. There, projects can be added with a command:

```bash
defaults write net.sourceforge.cruisecontrol.CCMenu Projects PROJECTS_INPUT_AS_JSON
```

**Comment by anaynayak** [comment]
I could see some of the reasons for doing this on the CCMenu discussion. Will have to explore a bit. Let me know if you are interested in making a PR.

**Comment by sparkmuse** [comment]
@anaynayak  if you give me a bit of guidance I could try it. At the moment I would not even know where to start.

**Comment by alo-id** [comment]
@anaynayak  have you had time to look into this?

**Comment by anaynayak** [comment]
Sadly I haven't been able to make time for this. Few things that crossed my mind when I thought about this:
1. I'm not sure if the projects.json format is mac settings specific. Otherwise we might run into issues importing it + keeping it compatible.
2. Currently we use [QSettings](https://github.com/anaynayak/buildnotify/blob/df2a759bbc9b041e67e4244831a69f2089271a76/buildnotifylib/config.py#L48) to store the information. I believe this maps to system specific file formats. We'd need a way to transform the projects.json to QSettings implementation.
3. If someone can help build that mapping (even in isolation, we can see how we'd like to integrate it into the app)
4. A very rudimentary way is to have it via a command line script param.
