### ISSUE TITLE
Preferences dialog: elements are fixed size

### ISSUE THREAD

**Issue by Bu11etmagnet** [anaynayak/buildnotify#43]
In the Preferences dialog, the Servers tab is fixed size even though the dialog itself is resizable. It would be nice if the list of monitored servers resized itself to fill the dialog.
This is less important than #30 (thanks for fixing that), because it's unlikely that there will be more monitored servers than would fit in the dialog. But [this](https://i.imgur.com/NULrJPm.png) looks ugly. 

Additionally, the OK button (and the other buttons in the Servers tab) can become invisible if the Preferences is resized to be more narrow than its original size. Perhaps resizing down should be forbidden.

**Comment by anaynayak** [comment]
This is now fixed in v1.0.4. You should be able to increase size and scroll through the projects Haven't handled the button resize making it invisible if the size is reduced. 

`pip install --pre --index-url https://test.pypi.org/simple buildnotify`

Let me know if that works. Will roll out 1.0.4 to pip shortly.

**Comment by anaynayak** [comment]
1.0.4 has been pushed to pypi as well

**Comment by Bu11etmagnet** [comment]
This now looks much nicer, with the list expanding and the buttons moving with the bottom/right edge of the dialog. Thanks for fixing it.

Buttons should not be resized. Setting a minimum height/width is perfectly adequate to ensure that all buttons are visible.
